name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main    # For production
      - develop # For testing
  pull_request:
    branches:
      - main
      - develop

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  DOCKER_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test with Maven
      run: mvn clean install -DskipTests

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE:latest .

    - name: Authenticate to GCR
      run: echo ${{ secrets.GCP_SA_KEY }} | docker login -u _json_key --password-stdin https://gcr.io

    - name: Push Docker image to GCR
      run: docker push $DOCKER_IMAGE:latest

  deploy-to-testing:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE - Testing
      run: |
        kubectl create namespace testing || true
        kubectl set image deployment/backend backend=$DOCKER_IMAGE:latest -n testing
        kubectl rollout status deployment/backend -n testing

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE - Production
      run: |
        kubectl create namespace production || true
        kubectl set image deployment/backend backend=$DOCKER_IMAGE:latest -n production
        kubectl rollout status deployment/backend -n production
