name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (testing or production)'
        required: true
        default: 'testing'
      
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  BACKEND_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: .

    - name: Verify Directory Structure
      run: |
          echo "Listing directory structure:"
          ls -R .
    
    - name: Print current directory
      run: pwd

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 23  

    - name: Build project with Maven
      run: mvn -B package --file backend/pom.xml
      
    - name: Set up GCloud CLI and authenticate to GCR
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_FILE }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io

    - name: Build Docker image
      run: docker build -t ${{ env.BACKEND_IMAGE }}:latest -f backend/Dockerfile .

    - name: Push Docker image to Container Registry
      run: docker push ${{ env.BACKEND_IMAGE }}:latest

  