name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  FRONTEND_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install 
      working-directory: Frontend

    - name: Build React app
      run: npm run build

    - name: Set up GCloud CLI and authenticate to Container Registry
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_FILE }}

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker gcr.io

    - name: Build Docker image
      run: docker build -t $FRONTEND_IMAGE:latest .

    - name: Push Docker image to GCR
      run: docker push $FRONTEND_IMAGE:latest

  deploy-to-testing:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS_FILE }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy frontend to GKE for testing
      run: |
        kubectl create namespace testing || true
        kubectl apply -f k8s/frontend-deployment.yaml --namespace=testing
        kubectl rollout status deployment/frontend -n testing

  deploy-to-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Set up GCloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials_json: ${{ secrets.GCP_CREDENTIALS_FILE }}

    - name: Set up kubectl
      run: |
        gcloud container clusters get-credentials my-cluster --zone us-central1-a --project ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy frontend to GKE for prod
      run: |
        kubectl create namespace production || true
        kubectl apply -f k8s/frontend-deployment.yaml --namespace=production
        kubectl rollout status deployment/frontend -n production
